import Footer from '@/components/common/Footer';
import SearchOverlay from '@/components/common/SearchOverlay';
import Header from '@/components/common/Header';
import type { Metadata } from 'next';
import './globals.css';
import Script from 'next/script';

export const metadata: Metadata = {
  title: 'Mannheimer Swartling - högkvalitativ affärsjuridisk rådgivning',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <meta charSet='utf-8' />
        <meta httpEquiv='x-ua-compatible' content='ie=edge' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <meta
          name='robots'
          content='index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1'
        />
        <link
          rel='alternate'
          href='https://www.mannheimerswartling.se/'
          hrefLang='sv'
        />
        <link
          rel='alternate'
          href='https://www.mannheimerswartling.se/en/'
          hrefLang='en'
        />
        <meta
          name='description'
          content='På Mannheimer Swartling möter du ett team med ett tydligt mål – att leverera den mest högkvalitativa affärsjuridiska rådgivningen.'
        />
        <link rel='canonical' href='https://www.mannheimerswartling.se/' />
        <meta property='og:locale' content='sv_SE' />
        <meta property='og:locale:alternate' content='en_GB' />
        <meta property='og:type' content='website' />
        <meta
          property='og:title'
          content='Mannheimer Swartling - högkvalitativ affärsjuridisk rådgivning'
        />
        <meta
          property='og:description'
          content='På Mannheimer Swartling möter du ett team med ett tydligt mål – att leverera den mest högkvalitativa affärsjuridiska rådgivningen.'
        />
        <meta property='og:url' content='https://www.mannheimerswartling.se/' />
        <meta property='og:site_name' content='Mannheimer Swartling' />
        <meta
          property='article:publisher'
          content='https://www.facebook.com/mannheimerswartling'
        />
        <meta
          property='article:modified_time'
          content='2024-08-21T07:33:59+00:00'
        />
        <meta
          property='og:image'
          content='https://www.mannheimerswartling.se/app/uploads/2021/05/mannheimer-swartling-entrance-logotype.jpeg'
        />
        <meta property='og:image:width' />
        <meta property='og:image:height' />
        <meta property='og:image:type' content='image/jpeg' />
        <meta name='twitter:card' content='summary_large_image' />
        <link rel='canonical' href='https://www.mannheimerswartling.se/' />
        <link
          rel='stylesheet'
          id='wp-block-library-css'
          href='https://www.mannheimerswartling.se/wp/wp-includes/css/dist/block-library/style.min.css?ver=57f4abb9429edb74bf5e6602e21d567f'
          media='all'
        />

        <link
          rel='stylesheet'
          id='ma_typekit-css'
          href='https://use.typekit.net/wvd5xcs.css?ver=1.0.2'
          media='all'
        />

        <link
          rel='https://api.w.org/'
          href='https://www.mannheimerswartling.se/wp-json/'
        />
        <link
          rel='alternate'
          type='application/json'
          href='https://www.mannheimerswartling.se/wp-json/wp/v2/pages/8380'
        />
        <link rel='shortlink' href='https://www.mannheimerswartling.se/' />
        <link
          rel='alternate'
          type='application/json+oembed'
          href='https://www.mannheimerswartling.se/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.mannheimerswartling.se%2F'
        />
        <link
          rel='alternate'
          type='text/xml+oembed'
          href='https://www.mannheimerswartling.se/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.mannheimerswartling.se%2F&#038;format=xml'
        />
        <link
          rel='icon'
          href='https://www.mannheimerswartling.se/app/uploads/2021/02/cropped-msa-favicon-black-32x32.png'
          sizes='32x32'
        />
        <link
          rel='icon'
          href='https://www.mannheimerswartling.se/app/uploads/2021/02/cropped-msa-favicon-black-192x192.png'
          sizes='192x192'
        />
        <link
          rel='apple-touch-icon'
          href='https://www.mannheimerswartling.se/app/uploads/2021/02/cropped-msa-favicon-black-180x180.png'
        />
        <meta
          name='msapplication-TileImage'
          content='https://www.mannheimerswartling.se/app/uploads/2021/02/cropped-msa-favicon-black-270x270.png'
        />
        <link
          rel='stylesheet'
          id='ma_styles-css'
          href='https://www.mannheimerswartling.se/app/themes/mannheimerswartling-theme/assets/css/app.css?ver=0.11.7.7'
          media='all'
        />
      </head>
      <body>
        <SearchOverlay />
        <Header />
        {children}
        <Footer />
        <Script
          type='application/ld+json'
          id='yoast-schema-graph'
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              '@context': 'https://schema.org',
              '@graph': [
                {
                  '@type': 'WebPage',
                  '@id': 'https://www.mannheimerswartling.se/',
                  url: 'https://www.mannheimerswartling.se/',
                  name: 'Mannheimer Swartling - högkvalitativ affärsjuridisk rådgivning',
                  isPartOf: {
                    '@id': 'https://www.mannheimerswartling.se/#website'
                  },
                  datePublished: '2020-11-06T10:18:50+00:00',
                  dateModified: '2024-08-21T07:33:59+00:00',
                  description:
                    'På Mannheimer Swartling möter du ett team med ett tydligt mål – att leverera den mest högkvalitativa affärsjuridiska rådgivningen.',
                  breadcrumb: {
                    '@id': 'https://www.mannheimerswartling.se/#breadcrumb'
                  },
                  inLanguage: 'sv-SE',
                  potentialAction: [
                    {
                      '@type': 'ReadAction',
                      target: ['https://www.mannheimerswartling.se/']
                    }
                  ]
                },
                {
                  '@type': 'BreadcrumbList',
                  '@id': 'https://www.mannheimerswartling.se/#breadcrumb',
                  itemListElement: [
                    {
                      '@type': 'ListItem',
                      position: 1,
                      name: 'Hem'
                    }
                  ]
                },
                {
                  '@type': 'WebSite',
                  '@id': 'https://www.mannheimerswartling.se/#website',
                  url: 'https://www.mannheimerswartling.se/',
                  name: 'Mannheimer Swartling',
                  description: '',
                  potentialAction: [
                    {
                      '@type': 'SearchAction',
                      target: {
                        '@type': 'EntryPoint',
                        urlTemplate:
                          'https://www.mannheimerswartling.se/?s={search_term_string}'
                      },
                      'query-input': 'required name=search_term_string'
                    }
                  ],
                  inLanguage: 'sv-SE'
                }
              ]
            })
          }}
          strategy='afterInteractive'
        />
        <Script
          async
          defer
          data-domain='mannheimerswartling.se'
          src='https://plausible.io/js/plausible.js'
          strategy='afterInteractive'
        />
        <Script
          id='ma_scripts-js-extra'
          dangerouslySetInnerHTML={{
            __html: `
            var siteData = {
                "home": "https://www.mannheimerswartling.se/",
                "restUrl": "https://www.mannheimerswartling.se/wp-json/",
                "themeUrl": "https://www.mannheimerswartling.se/app/themes/mannheimerswartling-theme",
                "newsUrl": "https://www.mannheimerswartling.se/nyheter/",
                "langCode": "sv",
                "translations": {
                    "showMediaButton": "Ladda fler bilder",
                    "nextPageButton": "Nästa sida",
                    "prevPageButton": "Föregående sida",
                    "categoryLabel": "Kategori",
                    "industryLabel": "Bransch",
                    "businessGroupLabel": "Verksamhetsområde",
                    "yearLabel": "År",
                    "positionLabel": "Position/Avdelning",
                    "officeLabel": "Kontor",
                    "searchPlaceholderNews": "Sök efter nyheter",
                    "searchPlaceholderCoworkers": "Sök efter medarbetare",
                    "resetFiltersText": "Rensa filter",
                    "noResultsTitle": "Hittade inga inlägg som matchar dina sökkriterier",
                    "showCoworkerBtnToggle": "Visa profiltext",
                    "hideCoworkerBtnToggle": "Göm profiltext"
                }
            };
          `
          }}
          strategy='afterInteractive'
        />
        <Script
          src='https://www.mannheimerswartling.se/app/themes/mannheimerswartling-theme/assets/js/dist/main.production.js?ver=0.11.7.7'
          id='ma_scripts-js'
        />
      </body>
    </html>
  );
}
